"""Clipboard change monitor.

Polls NSPasteboard.changeCount() in a background thread and records
text entries, excluding concealed/transient clipboard content from
password managers and WenZi itself.

Storage uses SQLite for incremental writes instead of full JSON dumps.
"""

from __future__ import annotations

import concurrent.futures
import hashlib
import json
import logging
import os
import sqlite3
import threading
import time
from dataclasses import dataclass, field
from typing import List, Optional

from wenzi.config import DEFAULT_CLIPBOARD_IMAGES_DIR, DEFAULT_ICON_CACHE_DIR

logger = logging.getLogger(__name__)

# Pasteboard types that indicate concealed/transient/sensitive content.
# Sources: nspasteboard.org standard + password manager / text expander conventions.
_CONCEALED_TYPES = frozenset({
    # nspasteboard.org standard types
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    # Password managers and text expanders
    "com.agilebits.onepassword",               # 1Password
    "de.petermaurer.TransientPasteboardType",   # TextExpander / Butler (legacy)
    "com.typeit4me.clipping",                   # TypeIt4Me
    "Pasteboard generator type",                # Typinator
    "net.antelle.keeweb",                       # KeeWeb
})

_MAX_TEXT_LENGTH = 10_240  # 10 KB


def _mask_text(text: str) -> str:
    """Mask text for logging, showing only first 2 and last 2 characters."""
    if len(text) <= 4:
        return "*" * len(text)
    return f"{text[:2]}..{text[-2:]}"
_MIN_IMAGE_DIM = 4  # ignore images smaller than 4×4 (tracking pixels, mock artifacts)
_MIN_OCR_DIM = 100  # below this, images rarely contain readable text

_DEFAULT_IMAGE_DIR = os.path.expanduser(DEFAULT_CLIPBOARD_IMAGES_DIR)
_DEFAULT_ICON_CACHE_DIR = os.path.expanduser(DEFAULT_ICON_CACHE_DIR)

_ICON_SIZE = 64  # 64x64 px for Retina display (rendered at 32x32 @2x)


def _icon_cache_path(icon_cache_dir: str, bundle_id: str) -> str:
    """Return the disk cache path for an app icon by bundle ID."""
    key = hashlib.md5(bundle_id.encode()).hexdigest()  # noqa: S324
    return os.path.join(icon_cache_dir, f"cb_{key}.png")


def _icon_fail_path(icon_cache_dir: str, bundle_id: str) -> str:
    """Return the sentinel path for a failed icon extraction."""
    key = hashlib.md5(bundle_id.encode()).hexdigest()  # noqa: S324
    return os.path.join(icon_cache_dir, f"cb_{key}.fail")


def _get_app_icon_png(bundle_id: str) -> Optional[bytes]:
    """Extract app icon as a 64x64 PNG by bundle identifier.

    Uses NSGraphicsContext.graphicsContextWithBitmapImageRep_ to draw
    the icon into a new bitmap at the target size.  This avoids mutating
    the shared NSImage returned by NSWorkspace and avoids lockFocus
    (setCurrentContext_ is thread-local, so this is safe from any thread).

    Returns None if the app is not found or icon extraction fails.
    """
    try:
        from AppKit import (
            NSBitmapImageRep,
            NSCalibratedRGBColorSpace,
            NSCompositingOperationSourceOver,
            NSGraphicsContext,
            NSPNGFileType,
            NSWorkspace,
        )
        from Foundation import NSMakeRect, NSZeroRect

        ws = NSWorkspace.sharedWorkspace()
        url = ws.URLForApplicationWithBundleIdentifier_(bundle_id)
        if url is None:
            return None
        icon = ws.iconForFile_(url.path())
        if icon is None:
            return None

        # Draw into a new bitmap at the exact pixel size we want.
        sz = _ICON_SIZE
        new_rep = NSBitmapImageRep.alloc() \
            .initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel_(  # noqa: E501
                None, sz, sz, 8, 4, True, False,
                NSCalibratedRGBColorSpace, 0, 0,
            )
        if new_rep is None:
            return None

        ctx = NSGraphicsContext.graphicsContextWithBitmapImageRep_(new_rep)
        if ctx is None:
            return None

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.setCurrentContext_(ctx)
        ctx.setImageInterpolation_(3)  # NSImageInterpolationHigh
        icon.drawInRect_fromRect_operation_fraction_(
            NSMakeRect(0, 0, sz, sz), NSZeroRect,
            NSCompositingOperationSourceOver, 1.0,
        )
        NSGraphicsContext.restoreGraphicsState()

        png = new_rep.representationUsingType_properties_(NSPNGFileType, {})
        return bytes(png) if png else None
    except Exception:
        logger.debug("Failed to extract icon for %s", bundle_id, exc_info=True)
        return None


@dataclass
class ClipboardEntry:
    """A single clipboard history entry."""

    text: str = ""
    timestamp: float = field(default_factory=time.time)
    source_app: str = ""
    source_bundle_id: str = ""  # e.g. "com.apple.Safari"
    image_path: str = ""  # filename in clipboard_images/ (empty = text entry)
    image_width: int = 0
    image_height: int = 0
    image_size: int = 0  # file size in bytes
    ocr_text: str = ""


# ---------------------------------------------------------------------------
# SQLite storage
# ---------------------------------------------------------------------------

_SCHEMA = """\
CREATE TABLE IF NOT EXISTS entries (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    text       TEXT    NOT NULL DEFAULT '',
    timestamp  REAL    NOT NULL,
    source_app TEXT    NOT NULL DEFAULT '',
    source_bundle_id TEXT NOT NULL DEFAULT '',
    image_path TEXT    NOT NULL DEFAULT '',
    image_width  INTEGER NOT NULL DEFAULT 0,
    image_height INTEGER NOT NULL DEFAULT 0,
    image_size   INTEGER NOT NULL DEFAULT 0,
    ocr_text     TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_entries_timestamp ON entries(timestamp);
"""


class _ClipboardDB:
    """Thin wrapper around a SQLite database for clipboard entries."""

    def __init__(self, db_path: str) -> None:
        self._path = db_path
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.executescript(_SCHEMA)
        # Migrate: add source_bundle_id column for existing databases
        try:
            self._conn.execute(
                "ALTER TABLE entries ADD COLUMN"
                " source_bundle_id TEXT NOT NULL DEFAULT ''"
            )
            self._conn.commit()
        except sqlite3.OperationalError:
            pass  # column already exists
        # Migrate: add ocr_text column for existing databases
        try:
            self._conn.execute(
                "ALTER TABLE entries ADD COLUMN"
                " ocr_text TEXT NOT NULL DEFAULT ''"
            )
            self._conn.commit()
        except sqlite3.OperationalError:
            pass  # column already exists

    def close(self) -> None:
        self._conn.close()

    # -- writes --

    def insert(self, entry: ClipboardEntry) -> None:
        self._conn.execute(
            "INSERT INTO entries"
            " (text, timestamp, source_app, source_bundle_id, image_path,"
            "  image_width, image_height, image_size, ocr_text)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                entry.text, entry.timestamp, entry.source_app,
                entry.source_bundle_id, entry.image_path,
                entry.image_width, entry.image_height, entry.image_size,
                entry.ocr_text,
            ),
        )
        self._conn.commit()

    def update_timestamp(self, **match) -> bool:
        """Set timestamp=now for the first row matching *match* kwargs.

        Returns True if a row was updated.
        """
        if not match:
            return False
        where = " AND ".join(f"{k}=?" for k in match)
        vals = list(match.values())
        cur = self._conn.execute(
            f"SELECT id FROM entries WHERE {where} LIMIT 1", vals,  # noqa: S608
        )
        row = cur.fetchone()
        if row is None:
            return False
        self._conn.execute(
            "UPDATE entries SET timestamp=? WHERE id=?",
            (time.time(), row[0]),
        )
        self._conn.commit()
        return True

    def delete_expired(self, max_days: int) -> List[str]:
        """Delete entries older than *max_days*. Returns removed image paths."""
        cutoff = time.time() - max_days * 86400
        cur = self._conn.execute(
            "SELECT image_path FROM entries"
            " WHERE timestamp < ? AND image_path != ''",
            (cutoff,),
        )
        removed = [row[0] for row in cur.fetchall()]
        self._conn.execute("DELETE FROM entries WHERE timestamp < ?", (cutoff,))
        self._conn.commit()
        return removed

    def delete_by_text(self, text: str) -> bool:
        """Delete the first entry matching *text*. Returns True if deleted."""
        cur = self._conn.execute(
            "SELECT id FROM entries WHERE text=? LIMIT 1", (text,),
        )
        row = cur.fetchone()
        if row is None:
            return False
        self._conn.execute("DELETE FROM entries WHERE id=?", (row[0],))
        self._conn.commit()
        return True

    def delete_by_image_path(self, image_path: str) -> bool:
        """Delete the first entry matching *image_path*. Returns True if deleted."""
        cur = self._conn.execute(
            "SELECT id FROM entries WHERE image_path=? LIMIT 1", (image_path,),
        )
        row = cur.fetchone()
        if row is None:
            return False
        self._conn.execute("DELETE FROM entries WHERE id=?", (row[0],))
        self._conn.commit()
        return True

    def delete_all(self) -> None:
        self._conn.execute("DELETE FROM entries")
        self._conn.commit()

    def delete_missing_images(self, image_dir: str) -> int:
        """Delete image entries whose files no longer exist on disk."""
        cur = self._conn.execute(
            "SELECT id, image_path FROM entries WHERE image_path != ''",
        )
        to_delete = []
        for row_id, img in cur.fetchall():
            if not os.path.isfile(os.path.join(image_dir, img)):
                to_delete.append(row_id)
        if to_delete:
            placeholders = ",".join("?" * len(to_delete))
            self._conn.execute(
                f"DELETE FROM entries WHERE id IN ({placeholders})",  # noqa: S608
                to_delete,
            )
            self._conn.commit()
        return len(to_delete)

    # -- reads --

    def load_all(self, max_days: int) -> List[ClipboardEntry]:
        """Return all non-expired entries, newest first."""
        cutoff = time.time() - max_days * 86400
        cur = self._conn.execute(
            "SELECT text, timestamp, source_app, source_bundle_id,"
            " image_path, image_width, image_height, image_size, ocr_text"
            " FROM entries WHERE timestamp >= ?"
            " ORDER BY timestamp DESC",
            (cutoff,),
        )
        return [
            ClipboardEntry(
                text=row[0], timestamp=row[1], source_app=row[2],
                source_bundle_id=row[3], image_path=row[4],
                image_width=row[5], image_height=row[6],
                image_size=row[7], ocr_text=row[8],
            )
            for row in cur.fetchall()
        ]

    def update_ocr_text(self, image_path: str, ocr_text: str) -> bool:
        """Update ocr_text for an image entry. Returns True if updated."""
        cur = self._conn.execute(
            "UPDATE entries SET ocr_text=? WHERE image_path=?",
            (ocr_text, image_path),
        )
        self._conn.commit()
        return cur.rowcount > 0

    def latest_text(self) -> str:
        """Return the text of the most recent entry, or ''."""
        cur = self._conn.execute(
            "SELECT text FROM entries ORDER BY timestamp DESC LIMIT 1",
        )
        row = cur.fetchone()
        return row[0] if row else ""

    def latest_image_path(self) -> str:
        """Return the image_path of the most recent entry, or ''."""
        cur = self._conn.execute(
            "SELECT image_path FROM entries ORDER BY timestamp DESC LIMIT 1",
        )
        row = cur.fetchone()
        return row[0] if row else ""


# ---------------------------------------------------------------------------
# JSON migration helper
# ---------------------------------------------------------------------------


def _migrate_json_to_db(json_path: str, db: _ClipboardDB) -> int:
    """Import entries from an old JSON file into the database.

    Returns the number of entries imported.  The JSON file is renamed
    to ``*.json.bak`` after successful migration.
    """
    if not os.path.isfile(json_path):
        return 0
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            return 0
        count = 0
        for d in data:
            if not isinstance(d, dict):
                continue
            entry = ClipboardEntry(
                text=d.get("text", ""),
                timestamp=d.get("timestamp", 0),
                source_app=d.get("source_app", ""),
                image_path=d.get("image_path", ""),
                image_width=d.get("image_width", 0),
                image_height=d.get("image_height", 0),
                image_size=d.get("image_size", 0),
            )
            db.insert(entry)
            count += 1
        # Rename old file so we don't re-import
        os.rename(json_path, json_path + ".bak")
        logger.info("Migrated %d entries from JSON to SQLite", count)
        return count
    except Exception:
        logger.debug("Failed to migrate JSON clipboard history", exc_info=True)
        return 0


# ---------------------------------------------------------------------------
# Monitor
# ---------------------------------------------------------------------------


class ClipboardMonitor:
    """Background monitor that records clipboard text changes.

    Polls NSPasteboard.changeCount() at a configurable interval and
    stores entries in memory (newest-first list) backed by SQLite.
    """

    def __init__(
        self,
        max_days: int = 7,
        poll_interval: float = 0.5,
        persist_path: Optional[str] = None,
        image_dir: Optional[str] = None,
        icon_cache_dir: Optional[str] = None,
        ocr_enabled: bool = True,
    ) -> None:
        self._max_days = max_days
        self._poll_interval = poll_interval
        self._persist_path = persist_path
        self._image_dir = image_dir or _DEFAULT_IMAGE_DIR
        self._icon_cache_dir = icon_cache_dir or _DEFAULT_ICON_CACHE_DIR
        self._entries: List[ClipboardEntry] = []
        self._lock = threading.Lock()
        self._version: int = 0
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._last_change_count: int = -1
        self._db: Optional[_ClipboardDB] = None
        self._ocr_executor: Optional[concurrent.futures.ThreadPoolExecutor] = None
        if ocr_enabled:
            self._ocr_executor = concurrent.futures.ThreadPoolExecutor(
                max_workers=1, thread_name_prefix="ocr",
            )

        if persist_path:
            self._init_db()

    def _init_db(self) -> None:
        """Open or create the SQLite database and load entries."""
        db_path = self._db_path()
        self._db = _ClipboardDB(db_path)

        # Migrate legacy JSON file if present
        json_path = self._persist_path
        if json_path and os.path.isfile(json_path):
            _migrate_json_to_db(json_path, self._db)

        # Clean up missing images and expired entries
        dropped = self._db.delete_missing_images(self._image_dir)
        if dropped:
            logger.info("Dropped %d clipboard entries (image files missing)", dropped)

        expired_images = self._db.delete_expired(self._max_days)
        if expired_images:
            logger.info(
                "Dropped %d expired clipboard entries (>%d days)",
                len(expired_images), self._max_days,
            )
            self._cleanup_image_files(expired_images)

        # Load into memory
        with self._lock:
            self._entries = self._db.load_all(self._max_days)
            self._version += 1
        logger.info("Loaded %d clipboard history entries", len(self._entries))

    def _db_path(self) -> str:
        """Derive the SQLite path from the persist_path."""
        # e.g. ~/.local/share/WenZi/clipboard_history.json
        #   -> ~/.local/share/WenZi/clipboard_history.db
        base = self._persist_path
        if base and base.endswith(".json"):
            return base[:-5] + ".db"
        return (base or "") + ".db"

    @property
    def image_dir(self) -> str:
        """Return the image directory used by this monitor instance."""
        return self._image_dir

    @staticmethod
    def default_image_dir() -> str:
        """Return the default directory for clipboard image storage."""
        return _DEFAULT_IMAGE_DIR

    @property
    def icon_cache_dir(self) -> str:
        """Return the icon cache directory used by this monitor."""
        return self._icon_cache_dir

    _ICON_FAIL_TTL = 600  # retry failed extractions after 10 minutes

    def _cache_app_icon(self, bundle_id: str) -> None:
        """Cache the app icon to disk if not already cached.

        Called from the polling thread after detecting a clipboard change.
        Writes a .fail sentinel on extraction failure; the sentinel
        expires after _ICON_FAIL_TTL seconds so transient failures
        are retried automatically.
        """
        if not bundle_id:
            return

        png_path = _icon_cache_path(self._icon_cache_dir, bundle_id)
        if os.path.isfile(png_path):
            return

        fail_path = _icon_fail_path(self._icon_cache_dir, bundle_id)
        try:
            if os.path.isfile(fail_path):
                age = time.time() - os.path.getmtime(fail_path)
                if age < self._ICON_FAIL_TTL:
                    return
                os.remove(fail_path)
        except OSError:
            pass

        png = _get_app_icon_png(bundle_id)
        try:
            os.makedirs(self._icon_cache_dir, exist_ok=True)
            if png is None:
                with open(fail_path, "wb") as f:
                    f.write(b"")
                return
            with open(png_path, "wb") as f:
                f.write(png)
        except Exception:
            logger.debug(
                "Failed to cache icon for %s", bundle_id, exc_info=True,
            )

    @property
    def entries(self) -> List[ClipboardEntry]:
        """Return a copy of the history (newest first)."""
        with self._lock:
            return list(self._entries)

    @property
    def version(self) -> int:
        """Monotonic counter incremented on every entries mutation."""
        with self._lock:
            return self._version

    def start(self) -> None:
        """Start the background polling thread."""
        if self._thread is not None and self._thread.is_alive():
            return

        self._stop_event.clear()

        # Capture current changeCount so we don't record existing content
        try:
            from AppKit import NSPasteboard

            pb = NSPasteboard.generalPasteboard()
            self._last_change_count = pb.changeCount()
        except Exception:
            self._last_change_count = -1

        self._thread = threading.Thread(target=self._poll_loop, daemon=True)
        self._thread.start()
        logger.info("Clipboard monitor started (interval=%.1fs)", self._poll_interval)

    def stop(self) -> None:
        """Stop the background polling thread."""
        self._stop_event.set()
        if self._thread is not None:
            self._thread.join(timeout=5.0)
            if self._thread.is_alive():
                logger.warning("Clipboard monitor thread did not stop in time")
            self._thread = None
        if self._ocr_executor is not None:
            self._ocr_executor.shutdown(wait=False)
            self._ocr_executor = None
        if self._db is not None:
            self._db.close()
            self._db = None
        logger.info("Clipboard monitor stopped")

    def clear(self) -> None:
        """Clear all history entries and associated image files."""
        with self._lock:
            self._entries.clear()
            self._version += 1
        if self._db:
            self._db.delete_all()
        self._clear_image_dir()

    def _poll_loop(self) -> None:
        """Main polling loop running in a background thread."""
        while not self._stop_event.is_set():
            try:
                self._check_clipboard()
            except Exception:
                logger.debug("Clipboard poll error", exc_info=True)
            self._stop_event.wait(self._poll_interval)

    def _check_clipboard(self) -> None:
        """Check if the clipboard has changed and record new content."""
        from AppKit import (
            NSPasteboard,
            NSPasteboardTypePNG,
            NSPasteboardTypeString,
            NSPasteboardTypeTIFF,
        )

        pb = NSPasteboard.generalPasteboard()
        current_count = pb.changeCount()

        if current_count == self._last_change_count:
            return

        self._last_change_count = current_count

        # Skip concealed/transient content (password managers, WenZi paste)
        if self._is_concealed(pb):
            logger.debug("Skipping concealed/transient clipboard entry")
            return

        # Detection order: PNG → text → TIFF.
        #
        # PNG is almost exclusively set when the user copies a real image
        # (browsers, image editors).  Checking it first ensures images are
        # not swallowed by the text branch (browsers also put the image URL
        # as text on the clipboard).
        #
        # TIFF is checked last because macOS commonly places a TIFF
        # *rendering* of rich text on the clipboard — treating it as an
        # image would create bogus image entries for every text copy.
        # TIFF-only (no PNG, no text) is the rare case where an app
        # provides only a TIFF image (e.g. Preview).
        source_app, source_bundle_id = self._get_frontmost_app()
        self._cache_app_icon(source_bundle_id)

        # PNG — if saved successfully, we're done; otherwise fall through
        # to text (the PNG may have been too small, e.g. a tracking pixel).
        png_data = pb.dataForType_(NSPasteboardTypePNG)
        if png_data is not None:
            if self._add_image_entry(
                bytes(png_data), "png", source_app, source_bundle_id,
            ):
                return

        text = pb.stringForType_(NSPasteboardTypeString)
        if text and str(text).strip():
            text_str = str(text).strip()
            if len(text_str) > _MAX_TEXT_LENGTH:
                logger.debug(
                    "Skipping clipboard text: %d chars exceeds 10 KB limit",
                    len(text_str),
                )
                return
            self._add_entry(text_str, source_app, source_bundle_id)
            return

        tiff_data = pb.dataForType_(NSPasteboardTypeTIFF)
        if tiff_data is not None:
            self._add_image_entry(
                bytes(tiff_data), "tiff", source_app, source_bundle_id,
            )

    @staticmethod
    def _is_concealed(pb) -> bool:
        """Check if the pasteboard contains concealed/transient markers."""
        types = pb.types()
        if types is None:
            return False
        return bool(_CONCEALED_TYPES.intersection(types))

    @staticmethod
    def _get_frontmost_app() -> tuple:
        """Return (name, bundle_id) of the frontmost application."""
        try:
            from AppKit import NSWorkspace

            workspace = NSWorkspace.sharedWorkspace()
            app = workspace.frontmostApplication()
            if app:
                name = str(app.localizedName()) if app.localizedName() else ""
                bundle_id = (
                    str(app.bundleIdentifier()) if app.bundleIdentifier() else ""
                )
                return name, bundle_id
        except Exception:
            pass
        return "", ""

    def promote(self, text: str) -> None:
        """Move an existing text entry to the top of the history list."""
        with self._lock:
            for i, entry in enumerate(self._entries):
                if entry.text == text:
                    self._entries.pop(i)
                    entry.timestamp = time.time()
                    self._entries.insert(0, entry)
                    self._version += 1
                    break
            else:
                return
        if self._db:
            self._db.update_timestamp(text=text)

    def promote_image(self, image_path: str) -> None:
        """Move an existing image entry to the top of the history list."""
        with self._lock:
            for i, entry in enumerate(self._entries):
                if entry.image_path == image_path:
                    self._entries.pop(i)
                    entry.timestamp = time.time()
                    self._entries.insert(0, entry)
                    self._version += 1
                    break
            else:
                return
        if self._db:
            self._db.update_timestamp(image_path=image_path)

    def delete_text(self, text: str) -> bool:
        """Delete a text entry from history. Returns True if found."""
        with self._lock:
            for i, entry in enumerate(self._entries):
                if entry.text == text:
                    self._entries.pop(i)
                    self._version += 1
                    break
            else:
                return False
        if self._db:
            self._db.delete_by_text(text)
        return True

    def delete_image(self, image_path: str) -> bool:
        """Delete an image entry and its file. Returns True if found."""
        with self._lock:
            for i, entry in enumerate(self._entries):
                if entry.image_path == image_path:
                    self._entries.pop(i)
                    self._version += 1
                    break
            else:
                return False
        if self._db:
            self._db.delete_by_image_path(image_path)
        self._cleanup_image_files([image_path])
        return True

    def _add_image_entry(
        self, image_data: bytes, image_type: str,
        source_app: str = "", source_bundle_id: str = "",
    ) -> bool:
        """Save image data to disk and add an image clipboard entry.

        Returns True if the entry was saved, False otherwise (e.g. image
        too small or invalid).
        """
        result = self._save_image(image_data, image_type)
        if result is None:
            return False

        filename, width, height, file_size = result

        entry = ClipboardEntry(
            text="",
            timestamp=time.time(),
            source_app=source_app,
            source_bundle_id=source_bundle_id,
            image_path=filename,
            image_width=width,
            image_height=height,
            image_size=file_size,
        )

        removed: List[str] = []
        with self._lock:
            # Skip if same as the most recent entry (by filename hash)
            if self._entries and self._entries[0].image_path == filename:
                return True  # already recorded, still counts as success
            self._entries.insert(0, entry)
            self._version += 1
            removed = self._trim_expired_locked()

        if self._db:
            self._db.insert(entry)
            if removed:
                self._db.delete_expired(self._max_days)

        if removed:
            self._cleanup_image_files(removed)
        logger.debug(
            "Clipboard image entry added: %s (%dx%d)", filename, width, height,
        )

        if (
            self._ocr_executor is not None
            and width >= _MIN_OCR_DIM
            and height >= _MIN_OCR_DIM
        ):
            filepath = os.path.join(self._image_dir, filename)
            self._ocr_executor.submit(self._run_ocr, filepath, filename)

        return True

    def _run_ocr(self, filepath: str, image_path: str) -> None:
        """Run OCR on an image file and update the entry (background thread)."""
        try:
            if self._stop_event.is_set():
                return

            from wenzi.scripting.ocr import recognize_text

            text = recognize_text(filepath)
            if not text:
                return

            if self._stop_event.is_set():
                return

            with self._lock:
                for entry in self._entries:
                    if entry.image_path == image_path:
                        entry.ocr_text = text
                        self._version += 1
                        break

            if self._db:
                self._db.update_ocr_text(image_path, text)

            logger.debug(
                "OCR completed for %s: %d chars", image_path, len(text),
            )
        except Exception:
            logger.debug("OCR failed for %s", image_path, exc_info=True)

    def _save_image(
        self, image_data: bytes, image_type: str
    ) -> Optional[tuple]:
        """Save image data as PNG, return (filename, width, height, size) or None."""
        try:
            from AppKit import NSBitmapImageRep, NSPNGFileType
            from Foundation import NSData

            ns_data = NSData.dataWithBytes_length_(image_data, len(image_data))
            rep = NSBitmapImageRep.imageRepWithData_(ns_data)
            if rep is None:
                return None

            width = int(rep.pixelsWide())
            height = int(rep.pixelsHigh())

            if width < _MIN_IMAGE_DIM or height < _MIN_IMAGE_DIM:
                logger.debug(
                    "Skipping tiny clipboard image: %dx%d", width, height,
                )
                return None

            # Convert to PNG if needed
            if image_type == "png":
                png_data = image_data
            else:
                png_ns = rep.representationUsingType_properties_(NSPNGFileType, {})
                if png_ns is None:
                    return None
                png_data = bytes(png_ns)

            # Generate filename: timestamp + hash of full content
            ts = int(time.time())
            content_hash = hashlib.sha256(png_data).hexdigest()[:12]
            filename = f"{ts}_{content_hash}.png"

            os.makedirs(self._image_dir, exist_ok=True)
            filepath = os.path.join(self._image_dir, filename)
            # Avoid overwriting an existing file (hash collision)
            suffix = 0
            while os.path.isfile(filepath):
                suffix += 1
                filename = f"{ts}_{content_hash}_{suffix}.png"
                filepath = os.path.join(self._image_dir, filename)
            with open(filepath, "wb") as f:
                f.write(png_data)

            return filename, width, height, len(png_data)
        except Exception:
            logger.debug("Failed to save clipboard image", exc_info=True)
            return None

    def _cleanup_image_files(self, filenames: List[str]) -> None:
        """Delete image files that are no longer referenced."""
        for fname in filenames:
            if not fname:
                continue
            path = os.path.join(self._image_dir, fname)
            try:
                if os.path.isfile(path):
                    os.remove(path)
                    logger.debug("Removed old clipboard image: %s", fname)
            except Exception:
                logger.debug("Failed to remove image %s", fname, exc_info=True)

    def _clear_image_dir(self) -> None:
        """Remove all files in the image directory."""
        try:
            if os.path.isdir(self._image_dir):
                for fname in os.listdir(self._image_dir):
                    fpath = os.path.join(self._image_dir, fname)
                    if os.path.isfile(fpath):
                        os.remove(fpath)
        except Exception:
            logger.debug("Failed to clear image directory", exc_info=True)

    def _add_entry(
        self, text: str, source_app: str = "", source_bundle_id: str = "",
    ) -> None:
        """Add a new entry, deduplicating consecutive identical texts."""
        entry = ClipboardEntry(
            text=text,
            timestamp=time.time(),
            source_app=source_app,
            source_bundle_id=source_bundle_id,
        )

        removed: List[str] = []
        with self._lock:
            # Skip if same as the most recent entry
            if self._entries and self._entries[0].text == text:
                return
            self._entries.insert(0, entry)
            self._version += 1
            removed = self._trim_expired_locked()

        if self._db:
            self._db.insert(entry)
            if removed:
                self._db.delete_expired(self._max_days)

        if removed:
            self._cleanup_image_files(removed)
        logger.debug("Clipboard entry added: %s (%d chars)", _mask_text(text), len(text))

    def _trim_expired_locked(self) -> List[str]:
        """Remove entries older than max_days. Must be called with _lock held.

        Returns a list of image filenames that were removed (for cleanup).
        """
        cutoff = time.time() - self._max_days * 86400
        kept = []
        removed_images: List[str] = []
        for entry in self._entries:
            if entry.timestamp >= cutoff:
                kept.append(entry)
            elif entry.image_path:
                removed_images.append(entry.image_path)
        self._entries = kept
        return removed_images
